# The URL the site will be built for
base_url = "http://localhost:1111"
title = "Marty Waweru"
theme = "duckquill"


# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

taxonomies = [
    { name = "tags", feed = true }
]

[markdown]

[markdown.highlighting]
theme = "catppuccin-mocha"

[extra]

styles = [
    "automation-terminal.css"
]

# Navigation

[extra.nav]
links = [
  { url = "/", name = "Home" },
  { url = "/projects/", name = "Projects" },
  { url = "/engineering-notes/", name = "Engineering Notes" },
  { url = "/resources/", name = "Resources" },
  { url = "/about/", name = "About" },
]

# Footer

[extra.footer]
show_copyright = true
copyright = "© Martin Waweru, 2026"
show_powered_by = true